<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>error handrimg</title>
  </head>
  <body>
    <script>
      // //num;
      // //console.log("실행");
      // console.log("아직 에러 없음");
      // num;
      // try {
      //   console.log("아직 에러 없음");
      //   getweather();
      //   //num;
      //   console.log("에러코드");
      // }catch(error){ //try구문에서 에러가 잡히면 catch에서 잡아줌.
      //   console.log(error);
      // }
      // console.log("try/catch 구문 밖 코드");

      // //보통 내부 코드 에러보다 외부 데이터를 불러올 떄 에러가 날 때 사용

      // try{
      //   setTimeout(() => {getWeather();}, 
      //   1000);
      // }catch(error){
      //   console.log(error);
      // }finally{
      //   console.log("에러가 나든 말든 발생1");
      // }
      // console.log("에러가 나든 말든 발생2");


    </script>
  </body>
</html>